const MEDIA = [
  // {
  //   artist: "Test",
  //   title: "test",
  //   track: "test.mp3",
  //   thumbnail: "test-w100.png",
  //   large: "test-w800.png",
  // },
  {
    artist: "Pink",
    title: "TRUSTFALL",
    track: "trustfall.mp3",
    thumbnail: "trustfall-w100.jpg",
    large: "trustfall-w800.jpg",
    banner: "trustfall-banner.jpg",
  },
  {
    artist: "Pink",
    title: "Never Gonna Not Dance Again",
    track: "never-gonna-not-dance-again.mp3",
    thumbnail: "trustfall-w100.jpg",
    large: "trustfall-w800.jpg",
    banner: "trustfall-banner.jpg",
  },
  {
    artist: "Selena Gomez & Marshmello",
    title: "Wolves",
    track: "wolves.mp3",
    thumbnail: "wolves-w100.jpg",
    large: "wolves-w800.jpg",
    banner: "wolves-banner.jpg",
  },
  {
    artist: "Original Broadway Cast Of Moulin Rouge! The Musical",
    title: "Crazy Rolling",
    track: "crazy-rolling.mp3",
    thumbnail: "moulin-rouge-w100.jpg",
    large: "moulin-rouge-w800.jpg",
    banner: "moulin-rouge-banner.jpg",
  },
  {
    artist: "Of Monsters and Men",
    title: "Little Talks",
    track: "little-talks.mp3",
    thumbnail: "little-talks-w100.jpg",
    large: "little-talks-w800.jpg",
    banner: "little-talks-banner.jpg",
  },
  {
    artist: "Defunctland",
    title: "Lines",
    track: "lines.mp3",
    thumbnail: "lines-w100.jpg",
    large: "lines-w800.jpg",
    banner: "lines-banner.jpg",
  },
  {
    artist: "Pink",
    title: "Blow Me (One last kiss)",
    track: "blow-me.mp3",
    thumbnail: "the-truth-about-love-w100.jpg",
    large: "the-truth-about-love-w800.jpg",
    banner: "the-truth-about-love-banner.jpg",
  },
  {
    artist: "Supershy & Tom Misch",
    title: "Happy Music",
    track: "happy-music.mp3",
    thumbnail: "happy-music-w100.jpg",
    large: "happy-music-w800.jpg",
    banner: "happy-music-banner.jpg",
  },
  {
    artist: "SIAMES",
    title: "Mr. Fear",
    track: "mr-fear.mp3",
    thumbnail: "mr-fear-w100.jpg",
    large: "mr-fear-w800.jpg",
    banner: "mr-fear-banner.jpg",
  },
  {
    artist: "Serena Ryder",
    title: "Stompa",
    track: "stompa.mp3",
    thumbnail: "harmony-w100.jpg",
    large: "harmony-w800.jpg",
    banner: "harmony-banner.jpg",
  },
];

export default MEDIA;
