const MEDIA = [
  {
    artist: "Pink",
    title: "Never Gonna Not Dance Again",
    track: "never-gonna-not-dance-again.mp3",
    album: "TRUSTFALL",
    thumbnail: "trustfall-w100.jpg",
    large: "trustfall-w800.png",
  },
  {
    artist: "Selena Gomez & Marshmello",
    title: "Wolves",
    track: "wolves.mp3",
    album: "Wolves (Single)",
    thumbnail: "wolves-w100.jpg",
    large: "wolves-w800.png",
  },
  {
    artist: "Original Broadway Cast Of Moulin Rouge! The Musical",
    title: "Crazy Rolling",
    track: "crazy-rolling.mp3",
    album: "Moulin Rouge! The Musical",
    thumbnail: "moulin-rouge-w100.jpg",
    large: "moulin-rouge-w800.jpg",
  },
  {
    artist: "Of Monsters and Men",
    title: "Little Talks",
    track: "little-talks.mp3",
    album: "My Head Is an Animal",
    thumbnail: "little-talks-w100.jpg",
    large: "little-talks-w800.jpg",
  },
  {
    artist: "Defunctland",
    title: "Lines",
    track: "lines.mp3",
    album: "Lines: Music for Waiting in Queues or Learning About Them",
    thumbnail: "lines-w100.jpg",
    large: "lines-w800.jpg",
  },
  {
    artist: "Pink",
    title: "Blow Me (One last kiss)",
    track: "blow-me.mp3",
    album: "The Truth About Love",
    thumbnail: "the-truth-about-love-w100.jpg",
    large: "the-truth-about-love-w800.png",
  },
  {
    artist: "Supershy & Tom Misch",
    title: "Happy Music",
    track: "happy-music.mp3",
    album: "Happy Music (Single)",
    thumbnail: "happy-music-w100.jpg",
    large: "happy-music-w800.jpg",
  },
  {
    artist: "SIAMES",
    title: "Mr. Fear",
    track: "mr-fear.mp3",
    album: "Bounce Into The Music",
    thumbnail: "mr-fear-w100.jpg",
    large: "mr-fear-w800.jpg",
  },
  {
    artist: "Pink",
    title: "Ave Mary A",
    track: "ave-mary-a.mp3",
    album: "Funhouse",
    thumbnail: "funhouse-w100.jpg",
    large: "funhouse-w800.jpg",
  },
  {
    artist: "Serena Ryder",
    title: "Stompa",
    track: "stompa.mp3",
    album: "Harmony",
    thumbnail: "harmony-w100.jpg",
    large: "harmony-w800.jpg",
  },
];

export default MEDIA;
